version: "3"
services:
  web:
    build: .
    ports:
     - "${PORT}:${PORT}"
    depends_on:
      - "mongo"
    working_dir: "/TrojansFC"
    command: "node keystone.js"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
