version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Test docker-compose
          command: |
            printf "PORT=${PORT} \n MONGO_URI=${MONGO_URI} \n COOKIE_SECRET=${COOKIE_SECRET} \n CLOUDINARY_URL=${CLOUDINARY_URL}" > .env 
            sudo docker-compose up --build -d