version: 2

jobs:
  build:
    docker: 
      # Primary container where all steps will be run
      - image: circleci/node:4.8.2
      # - machine: true
    steps:
      - checkout
      - run: 
          name: Test docker-compose
          command: |
            printf "PORT=${PORT} \n MONGO_URI=${MONGO_URI} \n COOKIE_SECRET=${COOKIE_SECRET} \n CLOUDINARY_URL=${CLOUDINARY_URL}"
            sudo docker-compose up --build 
            docker run --network container:contacts \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test