version: 2

jobs:
  build:
    docker: 
      # Primary container where all steps will be run
      # - image: circleci/node:4.8.2
      - machine: true
    steps:
      - checkout
      - run: docker-compose up --build
