version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Test docker-compose
          command: |
            printf "PORT=${PORT} \n MONGO_URI=${MONGO_URI} \n COOKIE_SECRET=${COOKIE_SECRET} \n CLOUDINARY_URL=${CLOUDINARY_URL}" > .env 
            sudo docker-compose up --build -d
            sudo docker network ls
            sudo docker run --network container:web \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost